server.port=8080

spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

management.endpoints.web.exposure.include=*

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=room-service
spring.cloud.gateway.routes[0].uri=lb://room-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/rooms/**

spring.cloud.gateway.routes[1].id=member-service
spring.cloud.gateway.routes[1].uri=lb://member-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/members/**

spring.cloud.gateway.routes[2].id=reservation-service
spring.cloud.gateway.routes[2].uri=lb://reservation-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/reservations/**